### PR TITLE
Added F-droid button

### PR DESCRIPTION
**Pull request by TechnologyClassroom**

### CODE REVIEW

**Comment by TheFakeMontyOnTheRun** [comment]
If you want to delve further, I would recommend taking a look at the "spin-off" https://github.com/TheFakeMontyOnTheRun/dungeons-of-noudar, much better organized (albeit not *really* finished).
Feel free to submit any change and ask anything.

**Comment by TechnologyClassroom** [comment]
These games remind me of the visual style of FromSoftware titles specifically Dark Souls and Knight's Field.  I played through Knights yesterday.  My thoughts on the game:

-The Knights are sort of disposable since they respawn after each level.  The first two levels I used a SWAT like strategy, but I eventually dropped all strategy and just ran each Knight individually.  The 2nd or 3rd would make it through to the end.

-A "fog of war" would make the game more interesting.  You can see the monsters approach from the other side of the map.  It would be more mysterious if the next room was unseen until you enter the door or a line of sight was added.

-Enemies approach based on direct lines of sight (vertically and horizontally).  They will approach even if there are walls between.  If there was fog of war, I may have missed this mechanic.

Good job on this!  I thought it was a cool little game.  It worked well on my Nexus 5X with CopperheadOS.  No crashes during play or using other applications.  I am impressed that the game size is much smaller than comparable games.

I will try to compile Dungeons of Noudar later this week.

**Comment by TheFakeMontyOnTheRun** [comment]
TBH, I have no plans on changing this codebase. What might happen is that I recreate this game using the noudar engine (this was it's original intent). The original concept for this was created during a game jam, and thus was very simple.

One cool thing I recommend you to try is, if you have a "cast" capable device (Chromecast, Android set-up-box connected to a TV or even a smartTV) is casting your screen - the 3D view will be displayed on the secondary display, while your phone will act as a controller.

If you have a bluetooth controller, it will also change the UI: the on-screen controllers will be removed from it. If you happen to use this while also connected to a secondary display, your phone will be mostly a status-display device.

**Comment by TechnologyClassroom** [comment]
I also thought it would be interesting to have a third top down view.  That is fair.  When I want delve into java, I may give it a try.

I had no idea that the game would do these cool things.  Maybe this should be stated in the HowTo or the README?

**Comment by TheFakeMontyOnTheRun** [comment]
Added some small info regarding the external controllers and casting on the README.
Regarding adding more cameras, suggest you take a look at: https://github.com/TheFakeMontyOnTheRun/knightsofalentejo/blob/master/KnightsOfAlentejoAndroid-AS/app/src/main/jni/GLES2Renderer.cpp#L304

Surprisingly, I had a top view (I recall adding this!) - not sure on it's status.
Originally, the game was top view only: http://ludumdare.com/compo/2011/05/27/the-knights-of-alentejo/

**Comment by TechnologyClassroom** [comment]
The latest version on F-Droid swaps between two camera modes kChaseOverview and kGlobalCamera.  With both views the monsters sometimes cannot be seen if they are one space above a wall.

The original reminds me of [Chip's Challenge](https://en.wikipedia.org/wiki/Chip%27s_Challenge) with battle elements.

**Pull request merged**
